# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tablero', 'Tablero'), ('union', 'Union'), ('apoyos', 'Apoyos')], max_length=10)),
                ('thickness', models.FloatField(default=0)),
                ('area', models.FloatField(default=0)),
                ('perimeter', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('veneer', models.CharField(choices=[('alpi1', 'alpi1'), ('alpi2', 'alpi2'), ('alpi3', 'alpi3'), ('alpi4', 'alpi4'), ('alpi5', 'alpi5'), ('alpi6', 'alpi6'), ('alpi7', 'alpi7'), ('alpi8', 'alpi8'), ('alpi9', 'alpi9'), ('alpi10', 'alpi10'), ('alpi11', 'alpi11'), ('contrach', 'contrach')], max_length=15)),
            ],
        ),
    ]
