# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpi1', models.FloatField(null=True)),
                ('alpi2', models.FloatField(null=True)),
                ('alpi3', models.FloatField(null=True)),
                ('alpi4', models.FloatField(null=True)),
                ('alpi5', models.FloatField(null=True)),
                ('alpi6', models.FloatField(null=True)),
                ('alpi7', models.FloatField(null=True)),
                ('alpi8', models.FloatField(null=True)),
                ('alpi9', models.FloatField(null=True)),
                ('alpi10', models.FloatField(null=True)),
                ('alpi11', models.FloatField(null=True)),
                ('contrach', models.FloatField(null=True)),
                ('prmt', models.FloatField(null=True)),
                ('qmm', models.FloatField(null=True)),
                ('dmm', models.FloatField(null=True)),
                ('tmm', models.FloatField(null=True)),
                ('T1', models.FloatField(null=True)),
                ('T2', models.FloatField(null=True)),
                ('T3', models.FloatField(null=True)),
                ('T4', models.FloatField(null=True)),
                ('T5', models.FloatField(null=True)),
                ('T6', models.FloatField(null=True)),
                ('P1', models.FloatField(null=True)),
                ('P2', models.FloatField(null=True)),
                ('P3', models.FloatField(null=True)),
                ('P4', models.FloatField(null=True)),
                ('P5', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Part',
        ),
    ]
